### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by MasterOfTheTiger** [angelali/threesjs#4]
There really should be mobile support. What is needed is:
- Make the board fill the full screen so you don’t have to zoom
- Add swipe ability or arrow buttons that appear for mobile

I do not know if the owner of this repo is active or not, but I would like to take a shot at this.

**Comment by angelali** [comment]
This repo is no longer active, but also, the lack of mobile support is intentional. threesjs was built as a loving desktop clone of [Threes!](http://asherv.com/threes/) back when it was only available on iOS. However, the original game has been ported to all major mobile platforms at this point, and I encourage you to go play the real thing!

**Comment by MasterOfTheTiger** [comment]
Oh, okay. I play the real thing, but I also love your version. Thanks for responding!
